sliders = SHADOWRES SHADOWDIST AMBIENT SUNBRIGHTNESS BRIGHTNESS SATURATION CONTRAST SHADOWSOFTNESS SHADOWBIAS BLOOMINTENSITY BLOOMRADIUS BLOOMTHRESHOLD SUNROTATION FOGOPACITY FOGSIZE FOGHEIGHT FOGTHICKNESS FOGSTEPS FOGDIST FOGLAYERS COLORTEMP
screen = [Quality] [Shadows] [Lighting] [Atmosphere] [Post] DISTANTHORIZONS LabPBR
screen.Quality = FANCYWATER FANCYFOG MATERIAL
screen.Shadows = SHADOWRES SHADOWDIST HARDWAREFILTERING HQSHADOWS SHADOWSOFTNESS SHADOWBIAS
screen.Lighting = AMBIENT SUNBRIGHTNESS SUNROTATION
screen.Atmosphere = [FancyFogConfig] FANCYFOG
screen.FancyFogConfig = FOGOPACITY FOGSIZE FOGTHICKNESS FOGSTEPS FOGDIST FOGLAYERS
screen.Post = BRIGHTNESS SATURATION CONTRAST COLORTEMP BLOOM BLOOMINTENSITY BLOOMRADIUS BLOOMTHRESHOLD