sliders = ShadowResolution ShadowDistance Ambient SunBrightness FogDensity Brightness Saturation ShadowSoftness BloomIntensity BloomRadius
screen = [Quality] [Shadows] [Lighting] [Atmosphere] [Post] DistantHorizons LabPBR
screen.Quality = FancyWater Material
screen.Shadows = ShadowResolution ShadowDistance HardwareFiltering HighQualityShadows ShadowSoftness
screen.Lighting = Ambient SunBrightness
screen.Atmosphere = FogDensity
screen.Post = Brightness Saturation Bloom BloomIntensity BloomRadius